"""info table

Revision ID: 683caf765db7
Revises: 
Create Date: 2022-01-09 20:50:56.219881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683caf765db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_content'), 'info', ['content'], unique=True)
    op.create_index(op.f('ix_info_title'), 'info', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_title'), table_name='info')
    op.drop_index(op.f('ix_info_content'), table_name='info')
    op.drop_table('info')
    # ### end Alembic commands ###
